// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.fabrician.webapp.globalvar.domain;

import org.fabrician.webapp.globalvar.domain.ArchiveVariableIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ArchiveVariableIntegrationTest_Roo_Configurable {
    
    declare @type: ArchiveVariableIntegrationTest: @Configurable;
    
}
