// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.fabrician.webapp.globalvar.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.fabrician.webapp.globalvar.domain.ComponentVariable;
import org.fabrician.webapp.globalvar.domain.ComponentVariableDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect ComponentVariableDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ComponentVariableDataOnDemand: @Component;
    
    private Random ComponentVariableDataOnDemand.rnd = new SecureRandom();
    
    private List<ComponentVariable> ComponentVariableDataOnDemand.data;
    
    public ComponentVariable ComponentVariableDataOnDemand.getNewTransientComponentVariable(int index) {
        ComponentVariable obj = new ComponentVariable();
        setEnvironment(obj, index);
        setGvName(obj, index);
        setGvValue(obj, index);
        setLocation(obj, index);
        setLogicalMachine(obj, index);
        setProject(obj, index);
        return obj;
    }
    
    public void ComponentVariableDataOnDemand.setEnvironment(ComponentVariable obj, int index) {
        String environment = "environment_" + index;
        if (environment.length() > 1024) {
            environment = environment.substring(0, 1024);
        }
        obj.setEnvironment(environment);
    }
    
    public void ComponentVariableDataOnDemand.setGvName(ComponentVariable obj, int index) {
        String gvName = "gvName_" + index;
        if (gvName.length() > 1024) {
            gvName = gvName.substring(0, 1024);
        }
        obj.setGvName(gvName);
    }
    
    public void ComponentVariableDataOnDemand.setGvValue(ComponentVariable obj, int index) {
        String gvValue = "gvValue_" + index;
        if (gvValue.length() > 1024) {
            gvValue = gvValue.substring(0, 1024);
        }
        obj.setGvValue(gvValue);
    }
    
    public void ComponentVariableDataOnDemand.setLocation(ComponentVariable obj, int index) {
        String location = "location_" + index;
        if (location.length() > 1024) {
            location = location.substring(0, 1024);
        }
        obj.setLocation(location);
    }
    
    public void ComponentVariableDataOnDemand.setLogicalMachine(ComponentVariable obj, int index) {
        String logicalMachine = "logicalMachine_" + index;
        if (logicalMachine.length() > 1024) {
            logicalMachine = logicalMachine.substring(0, 1024);
        }
        obj.setLogicalMachine(logicalMachine);
    }
    
    public void ComponentVariableDataOnDemand.setProject(ComponentVariable obj, int index) {
        String project = "project_" + index;
        if (project.length() > 1024) {
            project = project.substring(0, 1024);
        }
        obj.setProject(project);
    }
    
    public ComponentVariable ComponentVariableDataOnDemand.getSpecificComponentVariable(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ComponentVariable obj = data.get(index);
        Long id = obj.getId();
        return ComponentVariable.findComponentVariable(id);
    }
    
    public ComponentVariable ComponentVariableDataOnDemand.getRandomComponentVariable() {
        init();
        ComponentVariable obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ComponentVariable.findComponentVariable(id);
    }
    
    public boolean ComponentVariableDataOnDemand.modifyComponentVariable(ComponentVariable obj) {
        return false;
    }
    
    public void ComponentVariableDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ComponentVariable.findComponentVariableEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ComponentVariable' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ComponentVariable>();
        for (int i = 0; i < 10; i++) {
            ComponentVariable obj = getNewTransientComponentVariable(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
